#Library install and setup
# install.packages("ggplot2")
# install.packages("ggbeeswarm")
# install.packages('reshape')


library(ggplot2)
library(ggbeeswarm)
library("RODBC")
library("beeswarm")
library("dplyr")
library("reshape2")

#GLOBAL VARIABLES#
filesource = FALSE
dummydata = FALSE

#PRODDB
dbhandle <- odbcDriverConnect('driver={SQL Server};server=VICVOCMSQLP01;database=WICMASTER;uid=saVoc;pwd=Flinkle87')


#Create datasets from PROD DB with list of consult id's, consult and consult response details.
if (filesource == FALSE){
  write.csv(ds_users <- sqlQuery(dbhandle, "SELECT * FROM [WICMASTER].[dbo].[Users]"), 'dataset/ds_users.csv')
  write.csv(ds_message_ids <- sqlQuery(dbhandle, "SELECT *  FROM [WICMASTER].[dbo].[TextConversations] WHERE Created >'2017-09-10'"), 'dataset/ds_message_ids.csv')
  #ds_message_ids <- paste(ds_message_ids$ID, collapse=",")
  write.csv(ds_message_details <- sqlQuery(dbhandle, paste("SELECT [ID],[InTime]
                                                           ,[ConversationID]
                                                           ,[SeqNo]
                                                           ,[ClientID]
                                                           ,[EventID]
                                                           ,[ExternalTransactionID]
                                                           ,[CreatorMessageID]
                                                           ,[CreatorUserID]
                                                           ,[CreatorEndPoint]
                                                           ,[CreatorFirstName]
                                                           ,[CreatorMiddleName]
                                                           ,[CreatorLastName]
                                                           ,[CreatorSearchText]
                                                           ,[ParentID]
                                                           ,[ParentOwnerID]
                                                           ,[ParentResponseID]
                                                           ,[Expiration]
                                                           ,[RouteToVS]
                                                           ,[ScheduleInterval]
                                                           ,[ScheduleActivationTime]
                                                           ,[Activated]
                                                           ,[AutoGenerated]
                                                           ,[Severity]
                                                           ,[MCR]
                                                           ,[NotifyNoResponseSeconds]
                                                           ,[NotifyNoResponseTriggered]
                                                           ,[NotifyNoResponseDelivered]
                                                           ,[AttachmentGUID]
                                                           ,[WaveFilename]
                                                           ,[VoiceCallbackMethod]
                                                           ,[SentCount]
                                                           ,[DeliveredCount]
                                                           ,[FailedCount]
                                                           ,[OpenedCount]
                                                           ,[RespondedCount]
                                                           ,[CanceledCount]
                                                           ,[StatusCallID]
                                                           ,[StatisticUpdated]
                                                           FROM [WICMASTER].[dbo].[TextMessages] 
                                                           WHERE ConversationID IN (",paste(ds_message_ids$ID, collapse=","),") AND SeqNo =0", sep="")), 'dataset/ds_message_details.csv')
  write.csv(ds_message_response_details <- sqlQuery(dbhandle, paste("SELECT * FROM [WICMASTER].[dbo].[TextMessages] WHERE ConversationID IN (",paste(ds_message_ids$ID, collapse=","),") AND SeqNo =1", sep="")), 'dataset/ds_message_response_details.csv')
  odbcCloseAll()
} else{
  ds_users <- read.csv('dataset/ds_users.csv', fileEncoding="UTF-8-BOM")
  ds_message_ids <- read.csv('dataset/ds_message_ids.csv', fileEncoding="UTF-8-BOM")
  ds_message_details <- read.csv('dataset/ds_message_details.csv', fileEncoding="UTF-8-BOM")
  ds_message_response_details <- read.csv('dataset/ds_message_response_details.csv', fileEncoding="UTF-8-BOM")
}


#create message response data set
ds_response_times <- data.frame(conversationID= numeric(0), 
                                severity= numeric(0), 
                                consult_requestor_id= numeric(0),
                                consult_requestor_title= character(0),
                                consult_requestor_site = numeric(0),
                                consult_responder_id = numeric(0),
                                consult_responder_title= character(0),
                                request_datetime = character(0),
                                response_datetime = character(0),
                                response_time = character(0),
                                stringsAsFactors=FALSE)

#Cycle through the ds_message_details data set, and populate the ds_response_times with consult and response details
for (i in 1:nrow(ds_message_details))
  if (ds_message_details$ConversationID[i] %in% ds_message_response_details$ConversationID){
    ds_response_times[nrow(ds_response_times)+1,] <- c(ds_message_details$ConversationID[i], 
                                                       ds_message_details$Severity[i], 
                                                       ds_message_details$CreatorUserID[i],
                                                       toString(ds_users$Title[match(ds_message_details$CreatorUserID[i], ds_users$ID)]), 
                                                       ds_users$SiteID[match(ds_message_details$CreatorUserID[i], ds_users$ID)], 
                                                       consult_responder_id <- ds_message_response_details$CreatorUserID[match(ds_message_details$ConversationID[i], ds_message_response_details$ConversationID)], 
                                                       toString(ds_users$Title[match(consult_responder_id, ds_users$ID)]), 
                                                       # as.POSIXlt(as.numeric(ds_message_details$InTime[i]), origin = "1960-01-01"),
                                                       ds_message_details$InTime[i],
                                                       # as.POSIXlt(as.numeric(ds_message_response_details$InTime[i]), origin = "1960-01-01"),
                                                       ds_message_response_details$InTime[match(ds_message_details$ConversationID[i], ds_message_response_details$ConversationID)],
                                                       difftime(ds_message_response_details$InTime[i],ds_message_details$InTime[i], units="hours"))
    rm(consult_responder_id)
  }else{
    ds_response_times[nrow(ds_response_times)+1,] <- c(ds_message_details$ConversationID[i], 
                                                       ds_message_details$Severity[i], 
                                                       ds_message_details$CreatorUserID[i],
                                                       toString(ds_users$Title[match(ds_message_details$CreatorUserID[i], ds_users$ID)]),
                                                       ds_users$SiteID[match(ds_message_details$CreatorUserID[i], ds_users$ID)],
                                                       ds_message_response_details$CreatorUserID[i][match(ds_message_details$ConversationID[i], ds_message_response_details$ConversationID)],
                                                       "NO RESPONSE",
                                                       # toString(ds_users$Title[match(ds_message_response_details$CreatorUserID[i], ds_users$ID)]), 
                                                       # as.POSIXlt(as.numeric(ds_message_details$InTime[i]), origin = "1960-01-01"),
                                                       ds_message_details$InTime[i],
                                                       # as.POSIXlt(as.numeric(ds_message_details$InTime[i]), origin = "1960-01-01"), 
                                                       ds_message_details$InTime[i],
                                                       0)
  }

#convert the response date time to POSIX values, required to calculate date diff which is also done below.
ds_response_times$request_datetime <- as.POSIXct(as.numeric(ds_response_times$request_datetime), origin = "1970-01-01")
ds_response_times$response_datetime <- as.POSIXct(as.numeric(ds_response_times$response_datetime), origin = "1970-01-01")
ds_response_times$response_time <- difftime(ds_response_times$response_datetime,ds_response_times$request_datetime, units="hours")


#Replace literal NA value with NA/NULL values, Convert priority id into string equivelant and round response_times to 3 decimal places
ds_response_times$consult_requestor_title[ds_response_times$consult_requestor_title=="NA"] <-NA
ds_response_times$consult_responder_title[ds_response_times$consult_responder_title=="NA"] <-NA
ds_response_times$severity[ds_response_times$severity ==0] <-"Normal"
ds_response_times$severity[ds_response_times$severity ==1] <-"Urgent"
ds_response_times$severity[ds_response_times$severity ==2] <-"Priority"
ds_response_times$response_time <- round(as.numeric(ds_response_times$response_time), digits = 3)


#Since not all users in the system have a title populated, we will need to populate their titles with their fullname.
#Cycle through ds_response_time and populate missing titles for both requestor and responder
for (i in 1:nrow(ds_response_times))
  if (is.na(ds_response_times$consult_requestor_title[i])){
    ds_response_times$consult_requestor_title[i] <- toString(ds_users$DisplayName[match(ds_response_times$consult_requestor_id[i], ds_users$ID)])
  }

for (i in 1:nrow(ds_response_times))
  if (is.na(ds_response_times$consult_responder_title[i])){
    ds_response_times$consult_responder_title[i] <- toString(ds_users$DisplayName[match(ds_response_times$consult_responder_id[i], ds_users$ID)])
  }

if (dummydata == TRUE){
  ds_response_times <- read.csv("dataset/ds_dummy_response_times.csv")
}

#iterate through ds_response_time dataframe to assign a response flag for each thread.
for (i in 1:nrow(ds_response_times))
  if (ds_response_times$consult_responder_title[i] == "NO RESPONSE"){
    ds_response_times$response_flag[i] <- "N"
  }else{
    ds_response_times$response_flag[i] <- "Y"
  }

#Create a copy of the RAW dataset prior to removing automated alerts, non responders, specific sites
write.csv(ds_response_times, 'dataset/ds_response_times_RAW.csv')
#Store the total number of total message threads to date
total_messages_to_date <- nrow(ds_response_times)

#Calculate number of Vocera automated alerts (nurse call, bed side..) and remove.
total_alerts_to_date <- sum(ds_response_times$consult_requestor_id == "-2")
ds_response_times<-ds_response_times[!(ds_response_times$consult_requestor_id=="-2"),]


#Remove all sites that are not of interest from a report perspective.
ds_response_times<-ds_response_times[!is.na(ds_response_times$conversationID),]
#Exclude messages not responded to within 24hrs and store number of messages over 24hrs with no response
total_no_response_w24hrs <- nrow(ds_response_times[(ds_response_times$response_time>24),])
ds_response_times <- ds_response_times[(ds_response_times$response_time<24),]


#filter out by site
CRG_ds_response_times<-filter(ds_response_times, consult_requestor_site==2)
CVH_ds_response_times<-filter(ds_response_times, consult_requestor_site==4)
CVH_ds_response_times<-filter(CVH_ds_response_times, as.Date(request_datetime) > "2017-09-25")

#CALCULATE AND REMOVE ROWS WITH NO RESPONSES
total_no_response_to_date <- sum(ds_response_times$response_flag == "N")


#Calculate Daily summaries
#################CRG Site#####################################
# CRG_ds_response_times<- filter(ds_response_times, ds_response_times$consult_requestor_site == 2)
CRG_daily_response_summary <- data.frame(table(strftime(CRG_ds_response_times$request_datetime, format="%Y-%m-%d"), CRG_ds_response_times$response_flag))
CRG_daily_response_summary <- dcast(CRG_daily_response_summary, Var1 ~ Var2)
colnames(CRG_daily_response_summary) <- c("date", "#_no_responses", "#_responses")

#Add Summary Rows
CRG_daily_response_summary$total <- rowSums(CRG_daily_response_summary[,2:3])
CRG_daily_response_summary = mutate(CRG_daily_response_summary,
                                    total = CRG_daily_response_summary$`#_no_responses` + CRG_daily_response_summary$`#_responses`,
                                    no_response_pct = (CRG_daily_response_summary$`#_no_responses` / total)*100,
                                    response_pct = (CRG_daily_response_summary$`#_responses` / total)*100)

#################CVH Site#####################################
# CVH_ds_response_times<- filter(ds_response_times, ds_response_times$consult_requestor_site == 4)
CVH_daily_response_summary <- data.frame(table(strftime(CVH_ds_response_times$request_datetime, format="%Y-%m-%d"), CVH_ds_response_times$response_flag))
CVH_daily_response_summary <- dcast(CVH_daily_response_summary, Var1 ~ Var2)
colnames(CVH_daily_response_summary) <- c("date", "#_no_responses", "#_responses")

#Add Summary Rows
CVH_daily_response_summary$total <- rowSums(CVH_daily_response_summary[,2:3])
CVH_daily_response_summary = mutate(CVH_daily_response_summary,
                                    total = CVH_daily_response_summary$`#_no_responses` + CVH_daily_response_summary$`#_responses`,
                                    no_response_pct = (CVH_daily_response_summary$`#_no_responses` / total)*100,
                                    response_pct = (CVH_daily_response_summary$`#_responses` / total)*100)
##############################################################

#Remove rows with no response
ds_response_times<-ds_response_times[!(ds_response_times$response_flag == "N"),]
CRG_ds_response_times<-CRG_ds_response_times[!(CRG_ds_response_times$response_flag == "N"),]
CVH_ds_response_times<-CVH_ds_response_times[!(CVH_ds_response_times$response_flag == "N"),]

#SUMMARIZE ALL RESULTS:
############## CRG #############################################
CRG_mean_over_time <-data.frame(aggregate(CRG_ds_response_times$response_time, list(date=strftime(CRG_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=mean))
CRG_min_over_time <-data.frame(aggregate(CRG_ds_response_times$response_time, list(date=strftime(CRG_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=min))
#Due to the precision of the reporting, values less than 0.00 get truncated. Rounding to 0.001
CRG_min_over_time$x[CRG_min_over_time$x == 0] <- 0.001
CRG_max_over_time <-data.frame(aggregate(CRG_ds_response_times$response_time, list(date=strftime(CRG_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=max))
############## CVH #############################################
CVH_mean_over_time <-data.frame(aggregate(CVH_ds_response_times$response_time, list(date=strftime(CVH_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=mean))
CVH_min_over_time <-data.frame(aggregate(CVH_ds_response_times$response_time, list(date=strftime(CVH_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=min))
#Due to the precision of the reporting, values less than 0.00 get truncated. Rounding to 0.001
CVH_min_over_time$x[CVH_min_over_time$x == 0] <- 0.001
CVH_max_over_time <-data.frame(aggregate(CVH_ds_response_times$response_time, list(date=strftime(CVH_ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=max))

#Data clean up for threads that have the same responder as the requestor. This happens when the requestor sends the first and second message sequentially
# ############## CRG #############################################
# for (i in 1:nrow (CRG_ds_response_times)){
#   if (CRG_ds_response_times$consult_requestor_id[i] == CRG_ds_response_times$consult_responder_id[i] && CRG_ds_response_times$response_time < 0.01){
#     CRG_ds_response_times$new_mean[i] <- mean_over_time$x[match(strftime(ds_response_times$request_datetime[i], format="%Y-%m-%d"), strftime(mean_over_time$date, format="%Y-%m-%d"))]
#   }
# }
# ############## CVH #############################################
# for (i in 1:nrow (ds_response_times)){
#   if (ds_response_times$consult_requestor_id[i] == ds_response_times$consult_responder_id[i] && ds_response_times$response_time < 0.01){
#     ds_response_times$new_mean[i] <- mean_over_time$x[match(strftime(ds_response_times$request_datetime[i], format="%Y-%m-%d"), strftime(mean_over_time$date, format="%Y-%m-%d"))]
#   }
# }


#SUMMARIZE ALL RESULTS:
# mean_over_time <-data.frame(aggregate(ds_response_times$response_time, list(date=strftime(ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=mean))
# min_over_time <-data.frame(aggregate(ds_response_times$response_time, list(date=strftime(ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=min))
# max_over_time <-data.frame(aggregate(ds_response_times$response_time, list(date=strftime(ds_response_times$request_datetime, format="%Y-%m-%d")), FUN=max))


#DAILY RESPONSE TIME AVERAGES
############## CRG #############################################
CRG_daily_response_average <- merge(merge(CRG_mean_over_time, CRG_min_over_time, by = "date", all.x = TRUE, all.y=TRUE), CRG_max_over_time, by="date", all.x = TRUE, all.y = TRUE)
colnames(CRG_daily_response_average) <- c("date", "mean", "min", "max")

############## CVH #############################################
CVH_daily_response_average <- merge(merge(CVH_mean_over_time, CVH_min_over_time, by = "date", all.x = TRUE, all.y=TRUE), CVH_max_over_time, by="date", all.x = TRUE, all.y = TRUE)
colnames(CVH_daily_response_average) <- c("date", "mean", "min", "max")



# write.csv(ds_response_times, paste('reporting/response_times_', format(Sys.time(), "%Y_%m_%d"), ".csv"))
############## CRG #############################################
write.csv(CRG_daily_response_summary, paste('C:/Users/Public/NIH-Reporting/CRG_daily_msg_response_summary_', format(Sys.time(), "%Y_%m_%d"), ".csv"))
write.csv(CRG_daily_response_average, paste('C:/Users/Public/NIH-Reporting//CRG_daily_msg_response_average_', format(Sys.time(), "%Y_%m_%d"), ".csv"))

############## CVH #############################################
write.csv(CVH_daily_response_summary, paste('C:/Users/Public/NIH-Reporting/CVH_daily_msg_response_summary_', format(Sys.time(), "%Y_%m_%d"), ".csv"))
write.csv(CVH_daily_response_average, paste('C:/Users/Public/NIH-Reporting/CVH_daily_msg_response_average_', format(Sys.time(), "%Y_%m_%d"), ".csv"))
